-- Migration: 002_create_platform_tables
-- Description: Create Tier 1 (Platform Core) 
-- Created: 2025-11-28

-- ============================================
-- TIER 1: Platform Core Tables
-- ============================================

-- 1.1 plan - Subscription plans
CREATE TABLE IF NOT EXISTS plan (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(50) NOT NULL,
    display_name            VARCHAR(100) NOT NULL,
    description             TEXT,
    max_users               INTEGER,
    max_apps                INTEGER,
    price_monthly_cents     INTEGER DEFAULT 0,
    price_yearly_cents      INTEGER DEFAULT 0,
    is_active               BOOLEAN DEFAULT TRUE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_plan_name UNIQUE (name)
);

-- Seed plans
INSERT INTO plan (name, display_name, max_users, max_apps, price_monthly_cents) VALUES
    ('free', 'Free', 30, 50, 0),
    ('starter', 'Starter', 60, 100, 0),
    ('professional', 'Professional', 600, 500, 0),
    ('enterprise', 'Enterprise', NULL, NULL, NULL)
ON CONFLICT (name) DO NOTHING;

-- 1.2 role - User roles
CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(50) NOT NULL,
    display_name            VARCHAR(100) NOT NULL,
    description             TEXT,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_role_name UNIQUE (name)
);

-- Seed roles
INSERT INTO role (name, display_name) VALUES
    ('owner', 'Owner'),
    ('admin', 'Admin'),
    ('member', 'Member'),
    ('viewer', 'Viewer')
ON CONFLICT (name) DO NOTHING;

-- 1.3 organization - Customer accounts
CREATE TABLE IF NOT EXISTS organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    slug                    VARCHAR(100) NOT NULL,
    domain                  VARCHAR(255),
    logo_url                TEXT,
    plan_id                 INTEGER NOT NULL REFERENCES plan(id),
    status                  VARCHAR(50) NOT NULL DEFAULT 'pending_setup',
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_organization_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_organization_slug ON organization(slug);
CREATE INDEX IF NOT EXISTS idx_organization_domain ON organization(domain);
CREATE INDEX IF NOT EXISTS idx_organization_plan ON organization(plan_id);

-- 1.4 user - Platform users
CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         INTEGER NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    role_id                 INTEGER NOT NULL REFERENCES role(id),
    email                   VARCHAR(255) NOT NULL,
    full_name               VARCHAR(255),
    avatar_url              TEXT,
    provider_id             VARCHAR(255),
    email_verified           BOOLEAN DEFAULT FALSE,
    status                  VARCHAR(50) NOT NULL DEFAULT 'pending_invitation',
    invited_by_user_id      INTEGER REFERENCES "user"(id),
    invited_at              TIMESTAMP WITH TIME ZONE,
    joined_at               TIMESTAMP WITH TIME ZONE,
    last_login_at           TIMESTAMP WITH TIME ZONE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_user_provider_id UNIQUE (provider_id),
    CONSTRAINT uq_user_organization_email UNIQUE (organization_id, email)
);

CREATE INDEX IF NOT EXISTS idx_user_organization ON "user"(organization_id);
CREATE INDEX IF NOT EXISTS idx_user_email ON "user"(email);
CREATE INDEX IF NOT EXISTS idx_user_provider_id ON "user"(provider_id);
CREATE INDEX IF NOT EXISTS idx_user_status ON "user"(status);
CREATE INDEX IF NOT EXISTS idx_user_role ON "user"(role_id);

-- Record this migration
INSERT INTO schema_migrations (version, name) 
VALUES ('002', 'create_platform_tables')
ON CONFLICT (version) DO NOTHING;
