-- ============================================
-- TIER 2: Knowledge Base Tables
-- ============================================

-- 2.1 provider - Identity providers
CREATE TABLE IF NOT EXISTS provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(100) NOT NULL,
    slug                    VARCHAR(50) NOT NULL,
    display_name            VARCHAR(255) NOT NULL,
    description             TEXT,
    logo_url                TEXT,
    website_url             TEXT,
    documentation_url       TEXT,
    status                  VARCHAR(50) NOT NULL DEFAULT 'active',
    metadata                JSONB DEFAULT '{}',
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_provider_slug UNIQUE (slug)
);

-- Seed providers
INSERT INTO provider (name, slug, display_name, status) VALUES
    ('google_workspace', 'google-workspace', 'Google Workspace', 'active'),
    ('microsoft_365', 'microsoft-365', 'Microsoft 365', 'coming_soon')
ON CONFLICT (slug) DO NOTHING;

-- 2.2 category - App categories
CREATE TABLE IF NOT EXISTS category (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(100) NOT NULL,
    slug                    VARCHAR(50) NOT NULL,
    display_name            VARCHAR(255) NOT NULL,
    description             TEXT,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_category_slug UNIQUE (slug)
);

-- Seed categories
INSERT INTO category (name, slug, display_name) VALUES
    ('ai_ml', 'ai-ml', 'AI & Machine Learning'),
    ('productivity', 'productivity', 'Productivity'),
    ('storage', 'storage', 'Storage'),
    ('communication', 'communication', 'Communication'),
    ('development', 'development', 'Development'),
    ('security', 'security', 'Security'),
    ('other', 'other', 'Other')
ON CONFLICT (slug) DO NOTHING;

-- 2.3 product - Known third-party apps catalog
CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id             INTEGER REFERENCES provider(id),
    category_id             INTEGER REFERENCES category(id),
    name                    VARCHAR(255) NOT NULL,
    slug                    VARCHAR(100) NOT NULL,
    display_name            VARCHAR(255) NOT NULL,
    description             TEXT,
    logo_url                TEXT,
    website_url             TEXT,
    privacy_policy_url      TEXT,
    terms_url               TEXT,
    status                  VARCHAR(50) NOT NULL DEFAULT 'active',
    metadata                JSONB DEFAULT '{}',
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_product_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_product_provider ON product(provider_id);
CREATE INDEX IF NOT EXISTS idx_product_category ON product(category_id);
CREATE INDEX IF NOT EXISTS idx_product_status ON product(status);
CREATE INDEX IF NOT EXISTS idx_product_slug ON product(slug);

-- 2.4 product_auth_config - Authentication configurations
CREATE TABLE IF NOT EXISTS product_auth_config (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id              INTEGER REFERENCES product(id),
    provider_id             INTEGER REFERENCES provider(id),
    auth_type               VARCHAR(50) NOT NULL DEFAULT 'oauth2',
    client_id               VARCHAR(500),
    client_secret           VARCHAR(500),
    authorization_url       TEXT,
    token_url               TEXT,
    userinfo_url            TEXT,
    revoke_url              TEXT,
    scopes                  JSONB DEFAULT '[]',
    redirect_uri           TEXT,
    additional_params       JSONB DEFAULT '{}',
    is_active               BOOLEAN DEFAULT TRUE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_auth_config_product ON product_auth_config(product_id);
CREATE INDEX IF NOT EXISTS idx_product_auth_config_provider ON product_auth_config(provider_id);
CREATE INDEX IF NOT EXISTS idx_product_auth_config_type ON product_auth_config(auth_type);
CREATE INDEX IF NOT EXISTS idx_product_auth_config_active ON product_auth_config(is_active) WHERE is_active = TRUE;


-- Record this migration
INSERT INTO schema_migrations (version, name) 
VALUES ('003', 'create_knowledge_base_tables')
ON CONFLICT (version) DO NOTHING;