-- ============================================
-- TIER 3: Org Provider Connection Tables
-- ============================================

-- 3.1 org_provider_connection - Stores org's OAuth connection to providers
CREATE TABLE IF NOT EXISTS org_provider_connection (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    provider_id             BIGINT NOT NULL REFERENCES provider(id),
    connected_by_user_id    BIGINT NOT NULL REFERENCES "user"(id),
    
    -- Connection Status
    status                  VARCHAR(50) NOT NULL DEFAULT 'pending',
    
    -- OAuth Tokens (encrypted)
    access_token_encrypted  TEXT,
    refresh_token_encrypted TEXT,
    token_expires_at        TIMESTAMP WITH TIME ZONE,
    scopes_granted          JSONB DEFAULT '[]',
    
    -- Admin Info (who connected)
    admin_email             VARCHAR(255),
    workspace_domain        VARCHAR(255),
    
    -- Sync Tracking
    last_sync_started_at    TIMESTAMP WITH TIME ZONE,
    last_sync_completed_at  TIMESTAMP WITH TIME ZONE,
    last_sync_status        VARCHAR(50),
    last_sync_error         TEXT,
    
    -- Token Refresh Tracking
    last_token_refresh_at   TIMESTAMP WITH TIME ZONE,
    token_refresh_count     INTEGER DEFAULT 0,
    
    -- Error Tracking
    error_code              VARCHAR(100),
    error_message           TEXT,
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT uq_org_provider_conn_org_provider UNIQUE(organization_id, provider_id)
);

CREATE INDEX IF NOT EXISTS idx_org_provider_conn_org ON org_provider_connection(organization_id);
CREATE INDEX IF NOT EXISTS idx_org_provider_conn_provider ON org_provider_connection(provider_id);
CREATE INDEX IF NOT EXISTS idx_org_provider_conn_status ON org_provider_connection(status);
CREATE INDEX IF NOT EXISTS idx_org_provider_conn_connected_by ON org_provider_connection(connected_by_user_id);

-- Record this migration
INSERT INTO schema_migrations (version, name) 
VALUES ('005', 'create_org_connection_tables')
ON CONFLICT (version) DO NOTHING;
