-- ============================================
-- TIER 3: Identity Provider Connection Tables
-- ============================================

-- 3.1 identity_provider_connection - Stores org's OAuth connection to identity providers
CREATE TABLE IF NOT EXISTS identity_provider_connection (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    identity_provider_id    BIGINT NOT NULL REFERENCES identity_provider(id),
    connected_by_user_id    BIGINT NOT NULL REFERENCES "user"(id),
    
    -- Connection Status
    status                  VARCHAR(50) NOT NULL DEFAULT 'pending',
    
    -- OAuth Tokens (encrypted)
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at        TIMESTAMP WITH TIME ZONE,
    scopes_granted          JSONB DEFAULT '[]',
    
    -- Admin Info (who connected)
    admin_email             VARCHAR(255),
    workspace_domain        VARCHAR(255),
    
    -- Token Refresh Tracking
    last_token_refresh_at   TIMESTAMP WITH TIME ZONE,
    token_refresh_count     INTEGER DEFAULT 0,
    
    -- Error Tracking
    error_code              VARCHAR(100),
    error_message           TEXT,
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT uq_identity_provider_conn_org_provider UNIQUE(organization_id, identity_provider_id)
);

CREATE INDEX IF NOT EXISTS idx_identity_provider_conn_org ON identity_provider_connection(organization_id);
CREATE INDEX IF NOT EXISTS idx_identity_provider_conn_identity_provider ON identity_provider_connection(identity_provider_id);
CREATE INDEX IF NOT EXISTS idx_identity_provider_conn_status ON identity_provider_connection(status);
CREATE INDEX IF NOT EXISTS idx_identity_provider_conn_connected_by ON identity_provider_connection(connected_by_user_id);

-- Record this migration
INSERT INTO schema_migrations (version, name) 
VALUES ('005', 'create_org_connection_tables')
ON CONFLICT (version) DO NOTHING;
