-- ============================================
-- TIER 4: Discovery Tables
-- ============================================

-- 4.1 identity_user - Employees discovered from Google Workspace
CREATE TABLE IF NOT EXISTS identity_user (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    connection_id           BIGINT NOT NULL REFERENCES identity_provider_connection(id) ON DELETE CASCADE,
    
    -- Identity (from Directory API)
    provider_user_id        VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    full_name               VARCHAR(255),
    given_name              VARCHAR(255),
    family_name             VARCHAR(255),
    
    -- Role & Status
    is_admin                BOOLEAN DEFAULT FALSE,
    is_delegated_admin      BOOLEAN DEFAULT FALSE,
    status                  VARCHAR(50) NOT NULL DEFAULT 'active',
    
    -- Organization Unit
    org_unit_path           VARCHAR(500),
    
    -- Avatar
    avatar_url              TEXT,
    
    -- Raw API Response
    raw_data                JSONB DEFAULT '{}',
    
    -- Sync Tracking
    last_synced_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uq_workspace_user_org_provider_id UNIQUE(organization_id, provider_user_id)
);

CREATE INDEX IF NOT EXISTS idx_workspace_user_org ON identity_user(organization_id);
CREATE INDEX IF NOT EXISTS idx_workspace_user_connection ON identity_user(connection_id);
CREATE INDEX IF NOT EXISTS idx_workspace_user_email ON identity_user(email);
CREATE INDEX IF NOT EXISTS idx_workspace_user_provider_id ON identity_user(provider_user_id);
CREATE INDEX IF NOT EXISTS idx_workspace_user_status ON identity_user(status);


-- 4.2 identity_user_group - Groups discovered from Google Workspace
CREATE TABLE IF NOT EXISTS identity_user_group (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    connection_id           BIGINT NOT NULL REFERENCES identity_provider_connection(id) ON DELETE CASCADE,
    
    -- Identity (from Directory API)
    provider_group_id       VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    name                    VARCHAR(255) NOT NULL,
    description             TEXT,
    
    -- Counts
    direct_members_count    INTEGER DEFAULT 0,
    
    -- Raw API Response
    raw_data                JSONB DEFAULT '{}',
    
    -- Sync Tracking
    last_synced_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uq_workspace_group_org_provider_id UNIQUE(organization_id, provider_group_id)
);

CREATE INDEX IF NOT EXISTS idx_workspace_group_org ON identity_user_group(organization_id);
CREATE INDEX IF NOT EXISTS idx_workspace_group_connection ON identity_user_group(connection_id);
CREATE INDEX IF NOT EXISTS idx_workspace_group_email ON identity_user_group(email);


-- 4.3 group_membership - Links workspace users to groups
CREATE TABLE IF NOT EXISTS group_membership (
    identity_user_id       BIGINT NOT NULL REFERENCES identity_user(id) ON DELETE CASCADE,
    identity_user_group_id      BIGINT NOT NULL REFERENCES identity_user_group(id) ON DELETE CASCADE,
    
    -- Role within group (MEMBER, MANAGER, OWNER)
    role                    VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT pk_group_membership PRIMARY KEY (identity_user_id, identity_user_group_id)
);

CREATE INDEX IF NOT EXISTS idx_group_membership_user ON group_membership(identity_user_id);
CREATE INDEX IF NOT EXISTS idx_group_membership_group ON group_membership(identity_user_group_id);


-- Record this migration
INSERT INTO schema_migrations (version, name) 
VALUES ('006', 'create_discovery_tables')
ON CONFLICT (version) DO NOTHING;
