-- ============================================
-- TIER 4: Discovery Tables
-- ============================================

-- 4.1 workspace_user - Employees discovered from Google Workspace
CREATE TABLE IF NOT EXISTS workspace_user (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    connection_id           BIGINT NOT NULL REFERENCES org_provider_connection(id) ON DELETE CASCADE,
    
    -- Identity (from Directory API)
    provider_user_id        VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    full_name               VARCHAR(255),
    given_name              VARCHAR(255),
    family_name             VARCHAR(255),
    
    -- Role & Status
    is_admin                BOOLEAN DEFAULT FALSE,
    is_delegated_admin      BOOLEAN DEFAULT FALSE,
    status                  VARCHAR(50) NOT NULL DEFAULT 'active',
    
    -- Organization Unit
    org_unit_path           VARCHAR(500),
    
    -- Avatar
    avatar_url              TEXT,
    
    -- Raw API Response
    raw_data                JSONB DEFAULT '{}',
    
    -- Sync Tracking
    last_synced_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uq_workspace_user_org_provider_id UNIQUE(organization_id, provider_user_id)
);

CREATE INDEX IF NOT EXISTS idx_workspace_user_org ON workspace_user(organization_id);
CREATE INDEX IF NOT EXISTS idx_workspace_user_connection ON workspace_user(connection_id);
CREATE INDEX IF NOT EXISTS idx_workspace_user_email ON workspace_user(email);
CREATE INDEX IF NOT EXISTS idx_workspace_user_provider_id ON workspace_user(provider_user_id);
CREATE INDEX IF NOT EXISTS idx_workspace_user_status ON workspace_user(status);


-- 4.2 workspace_group - Groups discovered from Google Workspace
CREATE TABLE IF NOT EXISTS workspace_group (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    connection_id           BIGINT NOT NULL REFERENCES org_provider_connection(id) ON DELETE CASCADE,
    
    -- Identity (from Directory API)
    provider_group_id       VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    name                    VARCHAR(255) NOT NULL,
    description             TEXT,
    
    -- Counts
    direct_members_count    INTEGER DEFAULT 0,
    
    -- Raw API Response
    raw_data                JSONB DEFAULT '{}',
    
    -- Sync Tracking
    last_synced_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uq_workspace_group_org_provider_id UNIQUE(organization_id, provider_group_id)
);

CREATE INDEX IF NOT EXISTS idx_workspace_group_org ON workspace_group(organization_id);
CREATE INDEX IF NOT EXISTS idx_workspace_group_connection ON workspace_group(connection_id);
CREATE INDEX IF NOT EXISTS idx_workspace_group_email ON workspace_group(email);


-- 4.3 group_membership - Links workspace users to groups
CREATE TABLE IF NOT EXISTS group_membership (
    workspace_user_id       BIGINT NOT NULL REFERENCES workspace_user(id) ON DELETE CASCADE,
    workspace_group_id      BIGINT NOT NULL REFERENCES workspace_group(id) ON DELETE CASCADE,
    
    -- Role within group (MEMBER, MANAGER, OWNER)
    role                    VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT pk_group_membership PRIMARY KEY (workspace_user_id, workspace_group_id)
);

CREATE INDEX IF NOT EXISTS idx_group_membership_user ON group_membership(workspace_user_id);
CREATE INDEX IF NOT EXISTS idx_group_membership_group ON group_membership(workspace_group_id);


-- 4.4 discovered_app - Third-party apps discovered in workspace
CREATE TABLE IF NOT EXISTS discovered_app (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    connection_id           BIGINT NOT NULL REFERENCES org_provider_connection(id) ON DELETE CASCADE,
    
    -- App Identity (from Reports API)
    client_id               VARCHAR(500) NOT NULL,
    display_name            VARCHAR(500),
    
    -- Optional: Match to known product in our catalog
    product_id              BIGINT REFERENCES product(id),
    
    -- App Type
    client_type             VARCHAR(50),
    
    -- Status
    status                  VARCHAR(50) NOT NULL DEFAULT 'active',
    
    -- First & Last Seen
    first_seen_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_seen_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    -- Aggregated Scopes (union of all user authorizations)
    all_scopes              JSONB DEFAULT '[]',
    
    -- Raw API Response (first occurrence)
    raw_data                JSONB DEFAULT '{}',
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uq_discovered_app_org_client_id UNIQUE(organization_id, client_id)
);

CREATE INDEX IF NOT EXISTS idx_discovered_app_org ON discovered_app(organization_id);
CREATE INDEX IF NOT EXISTS idx_discovered_app_connection ON discovered_app(connection_id);
CREATE INDEX IF NOT EXISTS idx_discovered_app_client_id ON discovered_app(client_id);
CREATE INDEX IF NOT EXISTS idx_discovered_app_product ON discovered_app(product_id);
CREATE INDEX IF NOT EXISTS idx_discovered_app_status ON discovered_app(status);


-- 4.5 app_authorization - Which user authorized which app with what scopes
CREATE TABLE IF NOT EXISTS app_authorization (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discovered_app_id       BIGINT NOT NULL REFERENCES discovered_app(id) ON DELETE CASCADE,
    workspace_user_id       BIGINT NOT NULL REFERENCES workspace_user(id) ON DELETE CASCADE,
    
    -- Authorization Details
    scopes                  JSONB DEFAULT '[]',
    status                  VARCHAR(50) NOT NULL DEFAULT 'active',
    
    -- Timestamps (from Reports API)
    authorized_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at              TIMESTAMP WITH TIME ZONE,
    
    -- Raw API Response
    raw_data                JSONB DEFAULT '{}',
    
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT uq_app_auth_app_user UNIQUE(discovered_app_id, workspace_user_id)
);

CREATE INDEX IF NOT EXISTS idx_app_auth_app ON app_authorization(discovered_app_id);
CREATE INDEX IF NOT EXISTS idx_app_auth_user ON app_authorization(workspace_user_id);
CREATE INDEX IF NOT EXISTS idx_app_auth_status ON app_authorization(status);
CREATE INDEX IF NOT EXISTS idx_app_auth_authorized_at ON app_authorization(authorized_at);

-- Record this migration
INSERT INTO schema_migrations (version, name) 
VALUES ('006', 'create_discovery_tables')
ON CONFLICT (version) DO NOTHING;
