-- ============================================
-- TIER 5: Application Inventory & Risk Tables
-- ============================================

-- 5.1 oauth_app - Third-party applications
CREATE TABLE IF NOT EXISTS oauth_app (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES organization(id),
    connection_id BIGINT REFERENCES identity_provider_connection(id),

    client_id TEXT NOT NULL,
    name TEXT NOT NULL,
    
    risk_score INTEGER DEFAULT 0,
    is_system_app BOOLEAN DEFAULT FALSE, -- Noise Filter
    is_trusted BOOLEAN DEFAULT FALSE,
    
    scopes_summary TEXT[],
    image_url TEXT,
    
    raw_data JSONB DEFAULT '{}', -- REQUIRED: Store full API object
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT uq_oauth_app_client UNIQUE (connection_id, client_id)
);

CREATE INDEX IF NOT EXISTS idx_oauth_app_org ON oauth_app(organization_id);
CREATE INDEX IF NOT EXISTS idx_oauth_app_connection ON oauth_app(connection_id);
CREATE INDEX IF NOT EXISTS idx_oauth_app_client_id ON oauth_app(client_id);
CREATE INDEX IF NOT EXISTS idx_oauth_app_risk_score ON oauth_app(risk_score);


-- 5.2 app_grant - User <-> App authorizations
CREATE TABLE IF NOT EXISTS app_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES organization(id),
    connection_id BIGINT REFERENCES identity_provider_connection(id),
    
    user_id BIGINT REFERENCES identity_user(id),
    app_id BIGINT REFERENCES oauth_app(id),
    
    status VARCHAR(50) DEFAULT 'active',
    scopes TEXT[] NOT NULL,
    
    -- Timestamps
    granted_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_accessed_at TIMESTAMPTZ,
    
    raw_data JSONB DEFAULT '{}', -- REQUIRED: Store full token object
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT uq_app_grant_user_app UNIQUE (user_id, app_id)
);

CREATE INDEX IF NOT EXISTS idx_app_grant_org ON app_grant(organization_id);
CREATE INDEX IF NOT EXISTS idx_app_grant_user ON app_grant(user_id);
CREATE INDEX IF NOT EXISTS idx_app_grant_app ON app_grant(app_id);
CREATE INDEX IF NOT EXISTS idx_app_grant_status ON app_grant(status);


-- 5.3 oauth_event - Immutable Event Log
CREATE TABLE IF NOT EXISTS oauth_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES organization(id),
    connection_id BIGINT REFERENCES identity_provider_connection(id),
    
    user_id BIGINT REFERENCES identity_user(id),
    app_id BIGINT REFERENCES oauth_app(id),
    
    event_type VARCHAR(50) NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    
    raw_data JSONB DEFAULT '{}', -- REQUIRED: Store full event object
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_oauth_event_org ON oauth_event(organization_id);
CREATE INDEX IF NOT EXISTS idx_oauth_event_user ON oauth_event(user_id);
CREATE INDEX IF NOT EXISTS idx_oauth_event_app ON oauth_event(app_id);
CREATE INDEX IF NOT EXISTS idx_oauth_event_time ON oauth_event(event_time);


-- 5.4 crawl_history - Job Tracking
DO $$ BEGIN
    CREATE TYPE crawl_type AS ENUM ('users', 'groups', 'tokens', 'events', 'full');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE crawl_status AS ENUM ('running', 'success', 'error', 'partial');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS crawl_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES organization(id),
    connection_id BIGINT REFERENCES identity_provider_connection(id),

    crawl_type crawl_type NOT NULL,      -- e.g. 'users'
    status crawl_status NOT NULL,
    
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    
    error_message TEXT,
    stats_json JSONB,                    -- e.g. {"scanned": 100, "new": 5}
    raw_debug_json JSONB                 -- Optional debug info
);

CREATE INDEX IF NOT EXISTS idx_crawl_history_connection ON crawl_history(connection_id);
CREATE INDEX IF NOT EXISTS idx_crawl_history_status ON crawl_history(status);


-- Record this migration
INSERT INTO schema_migrations (version, name) 
VALUES ('007', 'create_app_inventory_tables')
ON CONFLICT (version) DO NOTHING;
